apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-epam-dev
  labels:
    app: nginx-epam
    owners: ValentinKozlov
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-epam
      owners: ValentinKozlov
      env: dev
  template:
    metadata:
      labels:
        app: nginx-epam
        owners: ValentinKozlov
        env: dev
    spec:
      containers:
      - name: nginx-epam-lesson1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"